name: Deploy WiseCents Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5E38F34B62024CF18CE49F36DF168D7C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9B0E92EA9C894D048D043326AFF9AD11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C70CC087FDDA40219FD64A387644FF7D }}

      - name: Deploy backend folder to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: wisecents-backend-dev
          slot-name: Production
          package: ./server
